name: iqrayukk_v2
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots- like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number- respectively.
# In Android- build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS- build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_webview_plugin: ^0.3.10+1
  http: ^0.12.0+4
  flame: ^0.22.1

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file- see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application- so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/image/bgMenuNonton.png
    - assets/image/bgMenuBelajar.png
    - assets/image/bgMenuMain.png
    - assets/image/MenuNonton.png
    - assets/image/MenuBelajar.png
    - assets/image/MenuMain.png
    - assets/image/iqra1-cover.png
    - assets/image/iqra1.1.png
    - assets/image/iqra1.2.png
    - assets/image/iqra1.3.png
    - assets/image/iqra1.4.png
    - assets/image/iqra1.5.png
    - assets/image/iqra1.6.png
    - assets/image/iqra1.7.png
    - assets/image/iqra1.8.png
    - assets/image/iqra1.9.png
    - assets/image/iqra1.10.png
    - assets/image/iqra1.11.png
    - assets/image/iqra1.12.png
    - assets/image/iqra1.13.png
    - assets/image/iqra1.14.png
    - assets/image/iqra1.15.png
    - assets/image/iqra1.16.png
    - assets/image/iqra1.17.png
    - assets/image/iqra1.18.png
    - assets/image/iqra1.19.png
    - assets/image/iqra1.20.png
    - assets/image/iqra1.21.png
    - assets/image/iqra1.22.png
    - assets/image/iqra1.23.png
    - assets/image/iqra1.24.png
    - assets/image/iqra1.25.png
    - assets/image/iqra1.26.png
    - assets/image/iqra1.27.png
    - assets/image/iqra1.28.png
    - assets/image/iqra1.29.png
    - assets/image/iqra1.30.png
    - assets/image/iqra1.31.png
    - assets/image/iqra2-cover.png
    - assets/image/iqra2.1.png
    - assets/image/iqra2.2.png
    - assets/image/iqra2.3.png
    - assets/image/iqra2.4.png
    - assets/image/iqra2.5.png
    - assets/image/iqra2.6.png
    - assets/image/iqra2.7.png
    - assets/image/iqra2.8.png
    - assets/image/iqra2.9.png
    - assets/image/iqra2.10.png
    - assets/image/iqra2.11.png
    - assets/image/iqra2.12.png
    - assets/image/iqra2.13.png
    - assets/image/iqra2.14.png
    - assets/image/iqra2.15.png
    - assets/image/iqra2.16.png
    - assets/image/iqra2.17.png
    - assets/image/iqra2.18.png
    - assets/image/iqra2.19.png
    - assets/image/iqra2.20.png
    - assets/image/iqra2.21.png
    - assets/image/iqra2.22.png
    - assets/image/iqra2.23.png
    - assets/image/iqra2.24.png
    - assets/image/iqra2.25.png
    - assets/image/iqra2.26.png
    - assets/image/iqra2.27.png
    - assets/image/iqra2.28.png
    - assets/image/iqra2.29.png
    - assets/image/iqra2.30.png
    - assets/image/iqra3-cover.png
    - assets/image/iqra3.1.png
    - assets/image/iqra3.2.png
    - assets/image/iqra3.3.png
    - assets/image/iqra3.4.png
    - assets/image/iqra3.5.png
    - assets/image/iqra3.6.png
    - assets/image/iqra3.7.png
    - assets/image/iqra3.8.png
    - assets/image/iqra3.9.png
    - assets/image/iqra3.10.png
    - assets/image/iqra3.11.png
    - assets/image/iqra3.12.png
    - assets/image/iqra3.13.png
    - assets/image/iqra3.14.png
    - assets/image/iqra3.15.png
    - assets/image/iqra3.16.png
    - assets/image/iqra3.17.png
    - assets/image/iqra3.18.png
    - assets/image/iqra3.19.png
    - assets/image/iqra3.20.png
    - assets/image/iqra3.21.png
    - assets/image/iqra3.22.png
    - assets/image/iqra3.23.png
    - assets/image/iqra3.24.png
    - assets/image/iqra3.25.png
    - assets/image/iqra3.26.png
    - assets/image/iqra3.27.png
    - assets/image/iqra3.28.png
    - assets/image/iqra3.29.png
    - assets/image/iqra3.30.png
    - assets/image/iqra4-cover.png
    - assets/image/iqra4.1.png
    - assets/image/iqra4.2.png
    - assets/image/iqra4.3.png
    - assets/image/iqra4.4.png
    - assets/image/iqra4.5.png
    - assets/image/iqra4.6.png
    - assets/image/iqra4.7.png
    - assets/image/iqra4.8.png
    - assets/image/iqra4.9.png
    - assets/image/iqra4.10.png
    - assets/image/iqra4.11.png
    - assets/image/iqra4.12.png
    - assets/image/iqra4.13.png
    - assets/image/iqra4.14.png
    - assets/image/iqra4.15.png
    - assets/image/iqra4.16.png
    - assets/image/iqra4.17.png
    - assets/image/iqra4.18.png
    - assets/image/iqra4.19.png
    - assets/image/iqra4.20.png 
    - assets/image/iqra4.21.png
    - assets/image/iqra4.22.png
    - assets/image/iqra4.23.png
    - assets/image/iqra4.24.png
    - assets/image/iqra4.25.png
    - assets/image/iqra4.26.png
    - assets/image/iqra4.27.png
    - assets/image/iqra4.28.png
    - assets/image/iqra4.29.png
    - assets/image/iqra4.30.png
    - assets/image/iqra5-cover.png
    - assets/image/iqra5.1.png
    - assets/image/iqra5.2.png
    - assets/image/iqra5.3.png
    - assets/image/iqra5.4.png
    - assets/image/iqra5.5.png
    - assets/image/iqra5.6.png
    - assets/image/iqra5.7.png
    - assets/image/iqra5.8.png
    - assets/image/iqra5.9.png
    - assets/image/iqra5.10.png
    - assets/image/iqra5.11.png
    - assets/image/iqra5.12.png
    - assets/image/iqra5.13.png
    - assets/image/iqra5.14.png
    - assets/image/iqra5.15.png
    - assets/image/iqra5.16.png
    - assets/image/iqra5.17.png
    - assets/image/iqra5.18.png
    - assets/image/iqra5.19.png
    - assets/image/iqra5.20.png
    - assets/image/iqra5.21.png
    - assets/image/iqra5.22.png
    - assets/image/iqra5.23.png
    - assets/image/iqra5.24.png
    - assets/image/iqra5.25.png
    - assets/image/iqra5.26.png
    - assets/image/iqra5.27.png
    - assets/image/iqra5.28.png
    - assets/image/iqra5.29.png
    - assets/image/iqra5.30.png
    - assets/image/iqra6-cover.png
    - assets/image/iqra6.1.png
    - assets/image/iqra6.2.png
    - assets/image/iqra6.3.png
    - assets/image/iqra6.4.png
    - assets/image/iqra6.5.png
    - assets/image/iqra6.6.png
    - assets/image/iqra6.7.png
    - assets/image/iqra6.8.png
    - assets/image/iqra6.9.png
    - assets/image/iqra6.10.png
    - assets/image/iqra6.11.png
    - assets/image/iqra6.12.png
    - assets/image/iqra6.13.png
    - assets/image/iqra6.14.png
    - assets/image/iqra6.15.png
    - assets/image/iqra6.16.png
    - assets/image/iqra6.17.png
    - assets/image/iqra6.18.png
    - assets/image/iqra6.19.png
    - assets/image/iqra6.20.png

  # To add assets to your application- add an assets section- like this:
  # assets:
  #  - assets/images/a_dot_burr.jpeg
  #  - assets/images/a_dot_ham.jpeg

  # An assets/image asset can refer to one or more resolution-specific "variants"- see
  # https://flutter.dev/assets-and-assets/images/#resolution-aware.

  # For details regarding adding assets from package dependencies- see
  # https://flutter.dev/assets-and-assets/images/#from-packages

  # To add custom fonts to your application- add a fonts section here-
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name- and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies-
  # see https://flutter.dev/custom-fonts/#from-packages
